name: Pyinstaller

on: 
  workflow_dispatch:
    inputs:
      fversion:
       description: 'Frontend Version'
       default: 'v0.'
       required: false
      releaseurl:
       description: 'Release URL'
       default: 'https://github.com/YeonV/LedFx-Frontend-v2/releases/tag/2.0.0-beta46'
       required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: LedFx/LedFx
        ref: main
        path: src
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
        spec: win.spec

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows
