name: Test Discord

on: 
  workflow_dispatch:

jobs:
  sendpost:
    name: Send Discord Post
    runs-on: [ubuntu-latest]
    steps:
    - name: Send Discord Post
      run: |
       curl -H "Content-Type: application/json" -d '{"content": "**DOWNLOAD:**&nbsp;&nbsp;&nbsp;&nbsp;<https://github.com/YeonV/LedFx-Builds/releases/tag/v2.0.84>\n\n**PREVIEW:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<https://preview.ledfx.app>\n\n**NOTE:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Please do not send messages here. Use the [testing]-Post instead!", "thread_name": "[blade-test]"}' ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
