name: DynamicMatrix

on:
  workflow_dispatch:
    inputs:
      macos:
        description: 'MacOS'
        default: true
        required: false
        type: boolean
      ubuntu:
        description: 'Ubuntu'
        default: true
        required: false
        type: boolean
      windows:
        description: 'Windows'
        default: true
        required: false
        type: boolean

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:    
    - name: Check Inputs and Prepare Matrix
      id: set-matrix
      run: |
        echo windows: ${{ github.event.inputs.windows }}
        echo ubuntu: ${{ github.event.inputs.ubuntu }}
        echo macos: ${{ github.event.inputs.macos }}

        os_list=()
        if [ "${{ github.event.inputs.windows }}" = "true" ]; then
          os_list+=('windows-latest')
        fi
        if [ "${{ github.event.inputs.ubuntu }}" = "true" ]; then
          os_list+=('ubuntu-latest')
        fi
        if [ "${{ github.event.inputs.macos }}" = "true" ]; then
          os_list+=('macos-latest')
        fi

        matrix_json="{\"os\": ["
        for os in "${os_list[@]}"; do
          matrix_json+="\"$os\","
        done
        matrix_json=${matrix_json%?} # remove trailing comma
        matrix_json+="], \"python-version\": [\"3.12.x\"]}"
        
        echo "$matrix_json" > matrix.json
        echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -x {0}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - name: Check Inputs again
      run: |
        echo windows: ${{ github.event.inputs.windows }}
        echo ubuntu: ${{ github.event.inputs.ubuntu }}
        echo macos: ${{ github.event.inputs.macos }}