name: New Build

on: 
  workflow_dispatch:
    inputs:
      fversion:
       description: 'Frontend Version'
       default: 'beta47'
       required: false
       
jobs:
  prepare:
    name: Prepare - Getting all files
    runs-on: [ubuntu-latest]
    outputs:
      bversion: ${{ steps.getbackendver.outputs.bversion }}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: LedFx/LedFx
        ref: main
        path: backend
    - name: Get Backendver
      id: getbackendver
      run: |
        cd backend/ledfx        
        echo "::set-output name=bversion::$(python consts.py | cut -d- -f1)"


  createrelease:
    name: Create Release v${{needs.prepare.outputs.bversion}}--${{ github.event.inputs.fversion }}
    runs-on: [ubuntu-latest]
    needs: prepare
    steps:
    - run: echo v${{needs.prepare.outputs.bversion}}--${{ github.event.inputs.fversion }}


  buildfrontend:
    name: Build Frontend
    runs-on: [ubuntu-latest]
    needs: prepare
    steps:
    - run: echo Build Frontend for Web
    - run: echo Upload Artifact Web
    - run: echo Build Frontend for App
    - run: echo Upload Artifact App

  core:
    name: Build Core
    runs-on: [ubuntu-latest]
    needs: createrelease
    steps:
    - run: echo Matrix Build Core

  client:
    name: Build Client
    runs-on: [ubuntu-latest]
    needs: buildfrontend
    steps:
    - run: echo Matrix Build Client

  cc:
    name: Build CC
    runs-on: [ubuntu-latest]
    needs: [core, buildfrontend]
    steps:
    - run: echo Matrix Build CC
